# ----- Project Name -----
spring.application.name=board_cafe_kiosk_2603
# ----- database Connection (MariaDB) -----
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
spring.datasource.url=jdbc:mariadb://localhost:3306/board_cafe_kiosk_2603
spring.datasource.username=admin
spring.datasource.password=0331
# ----- Log4j2 logging Levels -----
logging.level.org.springframework=info
logging.level.org.example.board_cafe_kiosk_2603=debug
# ----- Console log pattern -----
logging.level.org.mybatis=debug
logging.level.java.sql=debug
# logging pattern
logging.pattern.console=%clr(%-5level){green} %clr(%logger{36}.%M\\(\\)){cyan}: %msg%n
# ----- MyBatis Configuration -----
# ----- MyBatis: Location of Mapper XML files -----
# toss payments
toss.payments.secret-key=test_sk_YOUR_SECRET_KEY_HERE
toss.payments.confirm-url=https://api.tosspayments.com/v1/payments/confirm
# mybatis
mybatis.mapper-locations=classpath:mapper/**/*.xml
# ----- Convert snake_case (DB) to camelCase (Java) -----
mybatis.configuration.map-underscore-to-camel-case=true
# ----- [Windows] File Upload Settings -----
#spring.servlet.multipart.enabled=true
#spring.servlet.multipart.location=c:\\upload
#spring.servlet.multipart.max-request-size=30MB
#spring.servlet.multipart.max-file-size=10MB
#my.upload.path=c:\\upload
# ----- [MacOS] File Upload Settings -----
spring.servlet.multipart.enabled=true
spring.servlet.multipart.location=/Users/jy/upload
spring.servlet.multipart.max-request-size=30MB
spring.servlet.multipart.max-file-size=10MB
my.upload.path=/Users/jy/upload
# ----- spring security logging config -----
#logging.level.org.springframework.security=trace
# error detail
server.error.include-message=always
server.error.include-binding-errors=always
server.error.include-stacktrace=always
# ----- spring Batch -----
# spring Batch Table Auto Create
spring.batch.jdbc.initialize-schema=always
# Prevent Spring Batch from executing jobs automatically on startup
spring.batch.job.enabled=false